version: "3.8"
networks:
  copy-star:
    driver: bridge
volumes:
  dbdata:
    driver: local
services:
  backend:
    restart: unless-stopped
    expose:
      - "3004:3004"
    build:
      context: ./backend
    environment:
      LOGGING: "false"
      LOG_QUERY_PARAMETERS: "true"
      DB_TYPE: postgres
      DB_PASSWORD: 12345
      DB_NAME: CityAstrakhan
      FILE_SERVICE_DB_USER: CityAstrakhan-user
      FILE_SERVICE_DB_HOST: localhost
      PRIVATE_JWT_KEY: secret
      PORT: 3004
    depends_on:
      - postgres
    # networks:
    #   - copy-star
  postgres:
    image: postgres:city-astrakhan
    restart: always
    build:
      context: ./dbs/postgresql
      dockerfile: ./Dockerfile
    env_file:
      - ./dbs/postgresql/.env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    # networks:
    #   - copy-star
