psql --username "$POSTGRES_USER" <<EOF
CREATE DATABASE $POSTGRES_DB;

CREATE USER "$DB_USER" WITH PASSWORD '$POSTGRES_PASSWORD';

GRANT CONNECT ON DATABASE $POSTGRES_DB TO "$DB_USER";

GRANT USAGE ON SCHEMA public TO "$DB_USER";
EOF